/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import controller.Controller;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.CatchRegion;
import model.Fish;
import model.FishSort;
import model.Fisherman;

/**
 *
 * @author Aleksandra
 */
public class FishForm extends javax.swing.JDialog {
    private Controller kontroler;
    private MainForm mf;
    private Fish fishForChange;
    
    /**
     * Creates new form FishForm
     */
    
    
    public FishForm(java.awt.Frame parent, boolean modal, Fish f) {
        super(parent, modal);
        initComponents();
        kontroler = Controller.getInstance();
        this.mf = (MainForm) parent;
        fillComboBoxCaughtBy();

        if(f!=null){
            this.fishForChange=f;
            jTextFieldDaysSinceCatch.setText(String.valueOf(f.getDaysSinceCatch()));
            jTextFieldWeight.setText(String.valueOf(f.getWeight()));
            jTextFieldPricePerKg.setText(String.valueOf(f.getPricePerKg()));
            jComboBoxCatchRegion.setSelectedItem(f.getCatchRegion());
            jComboBoxCaughtBy.setSelectedItem(f.getCaughtBy());
            jComboBoxSortOfFish.setSelectedItem(f.getSortOfFish());
            jButtonAdd.setVisible(false);
        }else{
            jButtonChange.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSortOfFish = new javax.swing.JComboBox<>();
        jTextFieldWeight = new javax.swing.JTextField();
        jTextFieldPricePerKg = new javax.swing.JTextField();
        jTextFieldDaysSinceCatch = new javax.swing.JTextField();
        jComboBoxCatchRegion = new javax.swing.JComboBox<>();
        jComboBoxCaughtBy = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sort of fish");

        jLabel2.setText("Weight");

        jLabel3.setText("Price per kg");

        jLabel4.setText("Days since catch");

        jLabel5.setText("Caught by");

        jLabel6.setText("Catch region");

        jComboBoxSortOfFish.setModel(new DefaultComboBoxModel(FishSort.values()));

        jComboBoxCatchRegion.setModel(new DefaultComboBoxModel(CatchRegion.values()));

        jComboBoxCaughtBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCaughtByActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonChange.setText("Change");
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSortOfFish, 0, 308, Short.MAX_VALUE)
                            .addComponent(jTextFieldWeight)
                            .addComponent(jTextFieldPricePerKg)
                            .addComponent(jTextFieldDaysSinceCatch)
                            .addComponent(jComboBoxCatchRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCaughtBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonChange)
                        .addGap(18, 18, 18)))
                .addComponent(jButtonAdd)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSortOfFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPricePerKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDaysSinceCatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCaughtBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCatchRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonChange)
                    .addComponent(jButtonAdd))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        FishSort sort = (FishSort) jComboBoxSortOfFish.getSelectedItem();
        double weight = Double.parseDouble(jTextFieldWeight.getText());
        double pricePerKg = Double.parseDouble(jTextFieldPricePerKg.getText());
        int daysSinceCatch = Integer.parseInt(jTextFieldDaysSinceCatch.getText());
        Fisherman fisherman  = (Fisherman) jComboBoxCaughtBy.getSelectedItem();
        CatchRegion catchRegion = (CatchRegion) jComboBoxCatchRegion.getSelectedItem();
        
        Fish f = new Fish(sort, weight, pricePerKg, daysSinceCatch, fisherman, catchRegion);
        kontroler.addFish(f);
        
        JOptionPane.showMessageDialog(this, "Successfully added fish!", "Notification", JOptionPane.INFORMATION_MESSAGE);
        
        mf.refreshTable();
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        // TODO add your handling code here:
        FishSort sort = (FishSort) jComboBoxSortOfFish.getSelectedItem();
        double w = Double.parseDouble(jTextFieldWeight.getText());
        double ppkg = Double.parseDouble(jTextFieldPricePerKg.getText());
        int dsc = Integer.parseInt(jTextFieldDaysSinceCatch.getText());
        Fisherman f = (Fisherman) jComboBoxCaughtBy.getSelectedItem();
        CatchRegion cr = (CatchRegion) jComboBoxCatchRegion.getSelectedItem();
       
        fishForChange.setCatchRegion(cr);
        fishForChange.setCaughtBy(f);
        fishForChange.setDaysSinceCatch(dsc);
        fishForChange.setPricePerKg(ppkg);
        fishForChange.setSortOfFish(sort);
        fishForChange.setWeight(w);
        
        mf.refreshTable();
        JOptionPane.showMessageDialog(this, "Successfully changed row!", "Notification!", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jComboBoxCaughtByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCaughtByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCaughtByActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JComboBox<String> jComboBoxCatchRegion;
    private javax.swing.JComboBox<Fisherman> jComboBoxCaughtBy;
    private javax.swing.JComboBox<String> jComboBoxSortOfFish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldDaysSinceCatch;
    private javax.swing.JTextField jTextFieldPricePerKg;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables

    private void fillComboBoxCaughtBy() {
         jComboBoxCaughtBy.removeAllItems();
        List<Fisherman>  fishermenList = controller.Controller.getInstance().getFishermen();
        for(Fisherman f : fishermenList){
            jComboBoxCaughtBy.addItem(f);
        }
    }
}
